### PR TITLE
Resizeable Window variable & one fix.

### PR DESCRIPTION
**Pull request by mstudio45**
```diff
[ Fixed ]
+ Tab ScrollingFrame didn't resize properly with Config.Size (now it does)

[ Added ]
+ Resizeable variable in CreateWindow() function. This variable will make the window resizeable.
```

With Resizeable set to `true`:
<video src='https://user-images.githubusercontent.com/69036065/235355199-d06f4b9d-9d15-4002-b953-17c6848c5ae0.mp4' width=180/>

### CODE REVIEW

**Comment by violin-suzutsuki** [comment]
this feature is really nice but unfortunately it messes with the groupboxes - issue also happens when Resizeable = false:
https://imgsli.com/MTc1MDM1

**Comment by mstudio45** [comment]
Oh I see, Im going to fix the Groupboxes size and the issue, and make a new pull reuqest.

**Comment by mstudio45** [comment]
@violin-suzutsuki I have fixed the GroupBox size issue (its now accurate to the main release) and the `Resizeable = false` issue. I also added na "Delete Config" button to the SaveManager.lua

**Comment by violin-suzutsuki** [comment]
@mstudio45 thanks, the groupboxes are the correct size now but unfortunately still looks like there are a few issues:
screen1
screen2

**Comment by mstudio45** [comment]
My bad let me fix it real quick.

**Comment by mstudio45** [comment]
@violin-suzutsuki Fixed it, try now. If it doesn't work try waiting like 5 minutes for Github to update the raw link. I will fix it tommorow because I don't have time today if it doesn't work even after you have waited.

**Comment by violin-suzutsuki** [comment]
@mstudio45 yeah that stuff is fixed now, there's just some weird stuff with dropdowns not resizing properly and sometimes not even opening at all - might just be an issue with how dropdowns were implemented since the library wasn't built with scaling in mind:
dropdown

if you're not sure what the issue is feel free to merge into the dev branch instead and i can take a look

**Comment by mstudio45** [comment]
If you want you can find any bugs and I will fix them for you and then when its working fine you can merge this pull request to main. Also i will fix the dropdowns tommorow on my PC.

**Comment by mstudio45** [comment]
@violin-suzutsuki I have fixed the dropdowns. The issue was the list frame wasn't resizing when the dropdown opened. But there is one issue. The button is not large enough and I don't know whats happening because there is nothing wrong. That issue only happens on normal dropdowns without a SpecialType. I will update you if I will fix that. Thanks also for checking out this pull request!

I have also added `ClearTextOnFocus` for the AddInput function.

**Comment by mstudio45** [comment]
Made Keybinds not work if you are typing in chat or any other textbox.

**Comment by violin-suzutsuki** [comment]
merged into dev for the moment

**Comment by violin-suzutsuki** [comment]
@mstudio45 think i have got everything working on the dev branch, sliders & dropdowns seem to be fixed

**Comment by mstudio45** [comment]
Okay!

**Pull request merged**
